"""Heatmap rendering: splat per-patch attention onto a slide thumbnail.

Inputs are what the H5 already stores:
    coordinates       — (N_patches, 2) int  (x, y) at level-0 pixel space
    tissue_mask_lowres — (H_thumb, W_thumb) uint8/bool  binary tissue map

The H5 does NOT currently store `mask_downsample`, so we infer it from the
max patch coordinate + patch size. Acceptable for visualisation.

No matplotlib runtime dep — we ship a small magma LUT and blend with PIL.
"""

from __future__ import annotations

import numpy as np
from PIL import Image

# 256-entry magma-style RGB LUT built once at import.
# Generated by interpolating between 9 control colours sampled from
# matplotlib's `magma` so we don't take matplotlib as a runtime dep.
_CTRL = np.array(
    [
        [0, 0, 4],        # near-black
        [28, 16, 68],     # deep purple
        [79, 18, 123],    # purple
        [129, 37, 129],   # magenta-purple
        [181, 54, 122],   # magenta
        [229, 80, 100],   # red-pink
        [251, 135, 97],   # orange
        [254, 194, 135],  # peach
        [252, 253, 191],  # pale yellow
    ],
    dtype=np.float32,
)
_xs = np.linspace(0.0, 255.0, _CTRL.shape[0])
_grid = np.arange(256, dtype=np.float32)
_MAGMA_R = np.interp(_grid, _xs, _CTRL[:, 0]).astype(np.uint8)
_MAGMA_G = np.interp(_grid, _xs, _CTRL[:, 1]).astype(np.uint8)
_MAGMA_B = np.interp(_grid, _xs, _CTRL[:, 2]).astype(np.uint8)


def _infer_mask_downsample(coordinates: np.ndarray,
                           mask_shape: tuple[int, int],
                           patch_size_l0: int) -> float:
    """Estimate (level-0 px) / (thumbnail px) from the H5 contents."""
    H, W = mask_shape
    cx = int(coordinates[:, 0].max()) + patch_size_l0
    cy = int(coordinates[:, 1].max()) + patch_size_l0
    ds_x = cx / max(W, 1)
    ds_y = cy / max(H, 1)
    return float(max(ds_x, ds_y))


def attention_to_heatmap(
    attn: np.ndarray,
    coordinates: np.ndarray,
    mask_lowres: np.ndarray,
    patch_size_l0: int,
    mask_downsample: float | None = None,
) -> np.ndarray:
    """Splat per-patch attention into a 2-D heatmap at thumbnail resolution.

    Args:
        attn:           (N_patches,) float, sums to 1 (one sentence's attention).
        coordinates:    (N_patches, 2) level-0 (x, y) origins.
        mask_lowres:    (H_thumb, W_thumb) tissue mask — defines output shape.
        patch_size_l0:  patch edge in level-0 pixels (~896 at 20× over 40× native).
        mask_downsample: optional override; auto-inferred if None.

    Returns:
        (H_thumb, W_thumb) float32 heatmap, peak-normalised to [0, 1].
    """
    H, W = mask_lowres.shape
    if mask_downsample is None:
        mask_downsample = _infer_mask_downsample(coordinates, (H, W), patch_size_l0)
    edge_thumb = max(1, int(round(patch_size_l0 / mask_downsample)))

    heat = np.zeros((H, W), dtype=np.float32)
    xs = np.clip((coordinates[:, 0] / mask_downsample).astype(np.int32), 0, max(W - 1, 0))
    ys = np.clip((coordinates[:, 1] / mask_downsample).astype(np.int32), 0, max(H - 1, 0))
    for x, y, w in zip(xs, ys, attn):
        x0, y0 = int(x), int(y)
        x1 = min(W, x0 + edge_thumb)
        y1 = min(H, y0 + edge_thumb)
        if x1 > x0 and y1 > y0:
            block = heat[y0:y1, x0:x1]
            np.maximum(block, float(w), out=block)

    peak = float(heat.max())
    if peak > 1e-12:
        heat /= peak
    return heat


def _magma(values_uint8: np.ndarray) -> np.ndarray:
    """Map uint8 array → (H, W, 3) RGB uint8 via the magma LUT."""
    return np.stack(
        [_MAGMA_R[values_uint8], _MAGMA_G[values_uint8], _MAGMA_B[values_uint8]],
        axis=-1,
    )


def overlay_on_thumbnail(
    mask_lowres: np.ndarray,
    heatmap: np.ndarray,
    alpha: float = 0.55,
) -> Image.Image:
    """Render a greyscale tissue background with a magma heatmap overlaid.

    Args:
        mask_lowres: (H, W) tissue mask (uint8 / bool).
        heatmap:     (H, W) float in [0, 1].
        alpha:       blend weight for the heatmap (only where heatmap > 0).

    Returns:
        PIL.Image RGB, same H × W as the inputs.
    """
    mask = (np.asarray(mask_lowres) > 0).astype(np.uint8) * 200 + 30
    bg = np.stack([mask, mask, mask], axis=-1).astype(np.float32)

    heat_u8 = np.clip(heatmap * 255.0, 0, 255).astype(np.uint8)
    color = _magma(heat_u8).astype(np.float32)

    # Per-pixel blend weight: 0 where heatmap≈0, `alpha` where heatmap≈1
    w = (heatmap.astype(np.float32) * alpha)[:, :, None]
    blended = (1.0 - w) * bg + w * color
    return Image.fromarray(np.clip(blended, 0, 255).astype(np.uint8), mode="RGB")
